// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeaStyleOficial.Data;

#nullable disable

namespace NeaStyleOficial.Migrations
{
    [DbContext(typeof(NeaStyleContext))]
    [Migration("20260430195339_SeedAdm")]
    partial class SeedAdm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("ConjuntoProdutoSequence");

            modelBuilder.HasSequence("UsuarioSequence");

            modelBuilder.Entity("NeaStyleOficial.Models.Catalog.Produto", b =>
                {
                    b.Property<long>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProdutoId"));

                    b.Property<int>("CategoriaProduto")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstoqueAtual")
                        .HasColumnType("int");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TamanhoProduto")
                        .HasColumnType("int");

                    b.Property<int>("TipoProduto")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            ProdutoId = 1L,
                            CategoriaProduto = 1,
                            Cor = "Vermelho",
                            Descricao = "Vestido para formaturas e eventos.",
                            EstoqueAtual = 20,
                            ImagemUrl = "https://example.com/vestido-chique.jpg",
                            Nome = "Vestido Chique",
                            Preco = 299.90m,
                            PrecoCusto = 150.00m,
                            TamanhoProduto = 1,
                            TipoProduto = 2
                        },
                        new
                        {
                            ProdutoId = 2L,
                            CategoriaProduto = 0,
                            Cor = "Azul",
                            Descricao = "Calça para o dia a dia.",
                            EstoqueAtual = 15,
                            ImagemUrl = "https://example.com/calca-cargo.jpg",
                            Nome = "Calça Cargo",
                            Preco = 299.90m,
                            PrecoCusto = 160.00m,
                            TamanhoProduto = 2,
                            TipoProduto = 1
                        },
                        new
                        {
                            ProdutoId = 3L,
                            CategoriaProduto = 1,
                            Cor = "Preto",
                            Descricao = "Saia estilosa e versátil.",
                            EstoqueAtual = 25,
                            ImagemUrl = "https://example.com/saia-jeans.jpg",
                            Nome = "Saia Jeans",
                            Preco = 120.00m,
                            PrecoCusto = 90.00m,
                            TamanhoProduto = 0,
                            TipoProduto = 3
                        });
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Collections.ConjuntoProduto", b =>
                {
                    b.Property<long>("ConjuntoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR [ConjuntoProdutoSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<long>("ConjuntoProdutoId"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.HasKey("ConjuntoProdutoId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Collections.ItemConjunto", b =>
                {
                    b.Property<long>("ItemConjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemConjuntoId"));

                    b.Property<long>("ConjuntoProdutoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PedidoId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProdutoId1")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProdutoId2")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("ItemConjuntoId");

                    b.HasIndex("ConjuntoProdutoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ProdutoId1");

                    b.HasIndex("ProdutoId2");

                    b.ToTable("ItensConjunto", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Sales.Pagamento", b =>
                {
                    b.Property<long>("PagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PagamentoId"));

                    b.Property<int>("MetodoPagamento")
                        .HasColumnType("int");

                    b.Property<int>("Parcelas")
                        .HasColumnType("int");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusPagamento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagamentoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Sales.Pedido", b =>
                {
                    b.Property<long>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PedidoId"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ProdutoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PedidoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Sales.Reembolso", b =>
                {
                    b.Property<long>("ReembolsoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReembolsoId"));

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorReembolso")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReembolsoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Reembolsos", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Users.Usuario", b =>
                {
                    b.Property<long>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR [UsuarioSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<long>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Collections.Carrinho", b =>
                {
                    b.HasBaseType("NeaStyleOficial.Models.Collections.ConjuntoProduto");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.HasIndex("ClienteId");

                    b.ToTable("Carrinhos", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Collections.Favorito", b =>
                {
                    b.HasBaseType("NeaStyleOficial.Models.Collections.ConjuntoProduto");

                    b.HasIndex("ClienteId");

                    b.ToTable("Favoritos", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Users.Administrador", b =>
                {
                    b.HasBaseType("NeaStyleOficial.Models.Users.Usuario");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Administradores", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1L,
                            Email = "mariaclara4290@gmail.com",
                            Nome = "Admin Master",
                            Senha = "admin123",
                            Cargo = "Gerente"
                        });
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Users.Cliente", b =>
                {
                    b.HasBaseType("NeaStyleOficial.Models.Users.Usuario");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Collections.ItemConjunto", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.Collections.ConjuntoProduto", "Conjunto")
                        .WithMany("Itens")
                        .HasForeignKey("ConjuntoProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeaStyleOficial.Models.Sales.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId");

                    b.HasOne("NeaStyleOficial.Models.Catalog.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeaStyleOficial.Models.Catalog.Produto", null)
                        .WithMany("ItensConjunto")
                        .HasForeignKey("ProdutoId1");

                    b.HasOne("NeaStyleOficial.Models.Catalog.Produto", null)
                        .WithMany("ItensFavorito")
                        .HasForeignKey("ProdutoId2");

                    b.Navigation("Conjunto");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Sales.Pagamento", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.Sales.Pedido", "Pedido")
                        .WithMany("Pagamentos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Sales.Pedido", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.Users.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeaStyleOficial.Models.Catalog.Produto", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Sales.Reembolso", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.Sales.Pedido", "Pedido")
                        .WithMany("Reembolsos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Collections.Carrinho", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.Users.Cliente", "Cliente")
                        .WithMany("Carrinhos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Collections.Favorito", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.Users.Cliente", "Cliente")
                        .WithMany("Favoritos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Catalog.Produto", b =>
                {
                    b.Navigation("ItensConjunto");

                    b.Navigation("ItensFavorito");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Collections.ConjuntoProduto", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Sales.Pedido", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");

                    b.Navigation("Reembolsos");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Users.Cliente", b =>
                {
                    b.Navigation("Carrinhos");

                    b.Navigation("Favoritos");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
