// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeaStyleOficial.Data;

#nullable disable

namespace NeaStyleOficial.Migrations
{
    [DbContext(typeof(NeaStyleContext))]
    partial class NeaStyleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("ConjuntoProdutoSequence");

            modelBuilder.HasSequence("UsuarioSequence");

            modelBuilder.Entity("NeaStyleOficial.Models.ConjuntoProduto", b =>
                {
                    b.Property<long>("ConjuntoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR [ConjuntoProdutoSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<long>("ConjuntoProdutoId"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.HasKey("ConjuntoProdutoId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("NeaStyleOficial.Models.ItemConjunto", b =>
                {
                    b.Property<long>("ItemConjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemConjuntoId"));

                    b.Property<long>("ConjuntoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PedidoID")
                        .HasColumnType("bigint");

                    b.Property<long>("ProdutoID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProdutoID1")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProdutoID2")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("ItemConjuntoId");

                    b.HasIndex("ConjuntoId");

                    b.HasIndex("PedidoID");

                    b.HasIndex("ProdutoID");

                    b.HasIndex("ProdutoID1");

                    b.HasIndex("ProdutoID2");

                    b.ToTable("ItensConjunto", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Pagamento", b =>
                {
                    b.Property<long>("PagamentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PagamentoID"));

                    b.Property<int>("Metodo")
                        .HasColumnType("int");

                    b.Property<int>("MetodoPagamento")
                        .HasColumnType("int");

                    b.Property<long>("PedidoID")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StatusPagamento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagamentoID");

                    b.HasIndex("PedidoID");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Pedido", b =>
                {
                    b.Property<long>("PedidoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PedidoID"));

                    b.Property<long>("ClienteID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ProdutoID")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PedidoID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Produto", b =>
                {
                    b.Property<long>("ProdutoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProdutoID"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProdutoID");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Reembolso", b =>
                {
                    b.Property<long>("ReembolsoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReembolsoID"));

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PedidoID")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorReembolso")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReembolsoID");

                    b.HasIndex("PedidoID");

                    b.ToTable("Reembolsos", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Usuario", b =>
                {
                    b.Property<long>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR [UsuarioSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<long>("UsuarioID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioID");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Carrinho", b =>
                {
                    b.HasBaseType("NeaStyleOficial.Models.ConjuntoProduto");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.HasIndex("ClienteId");

                    b.ToTable("Carrinhos", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Favorito", b =>
                {
                    b.HasBaseType("NeaStyleOficial.Models.ConjuntoProduto");

                    b.HasIndex("ClienteId");

                    b.ToTable("Favoritos", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Administrador", b =>
                {
                    b.HasBaseType("NeaStyleOficial.Models.Usuario");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Administradores", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Cliente", b =>
                {
                    b.HasBaseType("NeaStyleOficial.Models.Usuario");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("NeaStyleOficial.Models.ItemConjunto", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.ConjuntoProduto", "Conjunto")
                        .WithMany("Itens")
                        .HasForeignKey("ConjuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeaStyleOficial.Models.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoID");

                    b.HasOne("NeaStyleOficial.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeaStyleOficial.Models.Produto", null)
                        .WithMany("ItensConjunto")
                        .HasForeignKey("ProdutoID1");

                    b.HasOne("NeaStyleOficial.Models.Produto", null)
                        .WithMany("ItensFavorito")
                        .HasForeignKey("ProdutoID2");

                    b.Navigation("Conjunto");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Pagamento", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.Pedido", "Pedido")
                        .WithMany("Pagamentos")
                        .HasForeignKey("PedidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Pedido", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeaStyleOficial.Models.Produto", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("ProdutoID");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Reembolso", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.Pedido", "Pedido")
                        .WithMany("Reembolsos")
                        .HasForeignKey("PedidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Carrinho", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.Cliente", "Cliente")
                        .WithMany("Carrinhos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Favorito", b =>
                {
                    b.HasOne("NeaStyleOficial.Models.Cliente", "Cliente")
                        .WithMany("Favoritos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.ConjuntoProduto", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Pedido", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");

                    b.Navigation("Reembolsos");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Produto", b =>
                {
                    b.Navigation("ItensConjunto");

                    b.Navigation("ItensFavorito");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("NeaStyleOficial.Models.Cliente", b =>
                {
                    b.Navigation("Carrinhos");

                    b.Navigation("Favoritos");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
